version: "3.9"
services:
  api:
    container_name: github-service
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    env_file:
      - .env
    command: pnpm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - redis
  redis:
    container_name: redis-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local
